# Generated by Django 3.2.6 on 2021-09-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('BTL', 'BridgeToLan'), ('NAT', 'NetworkAddressTranslation')], default='BTL', max_length=4)),
                ('config', models.JSONField(default=dict)),
                ('deactivated', models.BooleanField()),
                ('tags', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id')),
            ],
        ),
    ]
