# Generated by Django 3.2.6 on 2021-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnetwork',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
