# Generated by Django 3.2.6 on 2021-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmachines',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='firewall_rules',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
