# Generated by Django 3.2.6 on 2021-09-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('vmmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmachines',
            name='location',
        ),
        migrations.AddField(
            model_name='hostmachines',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='hostmachines',
            name='host_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hostmachines',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='key_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='instance_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='InstanceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_definition_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('instance_type', models.CharField(max_length=40)),
                ('instance_size', models.CharField(max_length=40)),
                ('cpu', models.CharField(max_length=40)),
                ('memory', models.CharField(max_length=40)),
                ('tags', models.JSONField(default=dict)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmmanager.hostmachines')),
            ],
        ),
    ]
