# Generated by Django 3.2.6 on 2021-09-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('vmmanager', '0002_auto_20210903_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('instance_type', models.CharField(max_length=40)),
                ('instance_size', models.CharField(max_length=40)),
                ('image_metadata', models.JSONField()),
                ('interfaces', models.JSONField()),
                ('storage', models.JSONField()),
                ('key_name', models.CharField(max_length=50)),
                ('firewall_rules', models.JSONField(null=True)),
                ('tags', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserKeys',
            new_name='UserKey',
        ),
        migrations.RemoveField(
            model_name='virtualmachines',
            name='account',
        ),
        migrations.RemoveField(
            model_name='virtualmachines',
            name='host',
        ),
        migrations.AlterField(
            model_name='instancedefinition',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmmanager.hostmachines', to_field='host_id'),
        ),
        migrations.RenameModel(
            old_name='HostMachines',
            new_name='HostMachine',
        ),
    ]
