# Generated by Django 3.2.6 on 2021-09-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0003_auto_20210917_0032'),
        ('vmmanager', '0003_auto_20210917_0032'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualMachines',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmmanager.hostmachine', to_field='host_id'),
        ),
    ]
