# Generated by Django 3.2.6 on 2021-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0004_auto_20210917_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
