# Generated by Django 3.2.6 on 2021-09-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0005_virtualmachine_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
