# Generated by Django 3.2.6 on 2021-10-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('vmmanager', '0006_delete_userkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('parent_image', models.CharField(max_length=60, null=True)),
                ('path', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('CREATING', 'Creating'), ('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('ATTACHED', 'Attached'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted'), ('ERROR', 'Error')], default='CREATING', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmmanager.hostmachine', to_field='host_id')),
                ('virtual_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vmmanager.virtualmachine', to_field='instance_id')),
            ],
        ),
    ]
