# Generated by Django 3.2.6 on 2021-10-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0007_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='format',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
