# Generated by Django 3.2.6 on 2021-10-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0008_auto_20211008_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='state',
            field=models.CharField(choices=[('CREATING', 'Creating'), ('AVAILABLE', 'Available'), ('TERMINATING', 'Terminating'), ('TERMINATED', 'Terminated'), ('ERROR', 'Error')], default='CREATING', max_length=16),
        ),
    ]
