# Generated by Django 3.2.6 on 2021-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0009_virtualmachine_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
