# Generated by Django 3.2.6 on 2021-10-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0010_virtualmachine_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='size',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmmanager.hostmachine', to_field='host_id'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='image_metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='interfaces',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='metadata',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='storage',
            field=models.JSONField(null=True),
        ),
    ]
