# Generated by Django 3.2.6 on 2021-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0011_auto_20211009_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
