# Generated by Django 3.2.6 on 2021-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0012_alter_volume_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('OTHER', 'Other')], default='LINUX', max_length=12, null=True),
        ),
    ]
