# Generated by Django 3.2.6 on 2021-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0013_volume_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('OTHER', 'Other'), ('NONE', 'None')], default='LINUX', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
