# Generated by Django 3.2.6 on 2021-10-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0014_auto_20211009_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='virtual_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmmanager.virtualmachine', to_field='instance_id'),
        ),
    ]
