# Generated by Django 3.2.6 on 2021-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0016_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.CharField(choices=[('CREATING', 'Creating'), ('AVAILABLE', 'Available'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted')], default='CREATING', max_length=16),
        ),
    ]
