# Generated by Django 3.2.6 on 2021-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='serverserviceaccounts',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccessaccounts',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
