# Generated by Django 3.2.6 on 2021-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20210828_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret',
            field=models.TextField(null=True),
        ),
    ]
