# Generated by Django 3.2.6 on 2021-08-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_user_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccessaccounts',
            old_name='auth_id',
            new_name='access_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='serverserviceaccounts',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.account', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='serverserviceaccounts',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='useraccessaccounts',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='useraccessaccounts',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
