# Generated by Django 3.2.6 on 2021-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestimage',
            old_name='image_metadata',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='image_metadata',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='guestimage',
            name='os',
            field=models.CharField(choices=[('WIN', 'Windows'), ('LNX', 'Linux'), ('OTH', 'Other')], default='LNX', max_length=3),
        ),
        migrations.AddField(
            model_name='userimage',
            name='os',
            field=models.CharField(choices=[('WIN', 'Windows'), ('LNX', 'Linux'), ('OTH', 'Other')], default='LNX', max_length=3),
        ),
    ]
