# Generated by Django 3.2.6 on 2021-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211001_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestimage',
            name='status',
            field=models.CharField(choices=[('1', 'Creating'), ('2', 'Ready'), ('3', 'Error'), ('4', 'Deleting'), ('5', 'Deleted')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='userimage',
            name='status',
            field=models.CharField(choices=[('1', 'Creating'), ('2', 'Ready'), ('3', 'Error'), ('4', 'Deleting'), ('5', 'Deleted')], default='1', max_length=1),
        ),
    ]
