# Generated by Django 3.2.6 on 2021-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20211007_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestimage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='status',
        ),
        migrations.AddField(
            model_name='guestimage',
            name='state',
            field=models.CharField(choices=[('CREATING', 'Creating'), ('READY', 'Ready'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted')], default='CREATING', max_length=16),
        ),
        migrations.AddField(
            model_name='userimage',
            name='state',
            field=models.CharField(choices=[('CREATING', 'Creating'), ('READY', 'Ready'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted')], default='CREATING', max_length=16),
        ),
    ]
