# Generated by Django 3.2.6 on 2021-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20211008_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestimage',
            name='os',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='os',
        ),
        migrations.AddField(
            model_name='guestimage',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('OTHER', 'Other')], default='LINUX', max_length=12),
        ),
        migrations.AddField(
            model_name='userimage',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('OTHER', 'Other')], default='LINUX', max_length=12),
        ),
    ]
