# Generated by Django 3.2.6 on 2021-09-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0003_auto_20210917_0032'),
        ('kube', '0002_alter_kubecluster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubecluster',
            name='associated_instances',
            field=models.ManyToManyField(to='vmmanager.VirtualMachine'),
        ),
        migrations.AlterField(
            model_name='kubecluster',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_controller', to='vmmanager.virtualmachine', to_field='instance_id'),
        ),
    ]
