# Generated by Django 3.2.6 on 2021-11-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0003_auto_20210917_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubecluster',
            name='type',
        ),
    ]
