# Generated by Django 3.2.6 on 2022-01-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0004_remove_kubecluster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubecluster',
            name='status',
            field=models.CharField(choices=[('Building', 'Building'), ('Failed', 'Failed'), ('Ready', 'Ready'), ('Updating', 'Updating'), ('Deleting', 'Deleting'), ('Terminated', 'Terminated')], default='Building', max_length=20),
        ),
    ]
