# Generated by Django 3.2.6 on 2022-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0005_alter_kubecluster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubecluster',
            name='status',
            field=models.CharField(choices=[('BUILDING', 'Building'), ('FAILED', 'Failed'), ('READY', 'Ready'), ('UPDATING', 'Updating'), ('DELETING', 'Deleting'), ('TERMINATED', 'Terminated')], default='BUILDING', max_length=20),
        ),
    ]
