# Generated by Django 3.2.6 on 2022-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0006_alter_kubecluster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubecluster',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
