# Generated by Django 3.2.6 on 2022-02-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0007_kubecluster_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kubecluster',
            old_name='image_metadata',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='kubecluster',
            name='minimum_requirements',
        ),
    ]
