# Generated by Django 4.0.2 on 2022-02-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kube', '0008_auto_20220205_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubecluster',
            name='version',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
